trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "./AssetManagement.sln"
  reactAppPath: "./src/ASM.Web"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  vmImageName: "ubuntu-latest"

stages:
  - stage: CI
    displayName: CI stage

    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "22.0.0"

          - task: UseDotNet@2
            inputs:
              version: "8.0.204"

          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: "restore"
              publishWebProjects: true
              projects: $(solution)

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: "build"
              projects: $(solution)
              arguments: --configuration $(buildConfiguration)

          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: "test"
              projects: $(solution)
              publishTestResults: false
              arguments: '--collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutput=./TestResults /p:CoverletOutputFormat=cobertura'

          - task: reportgenerator@5
            displayName: Generate Test Report
            inputs:
              reports: "$(Build.SourcesDirectory)/tests/**/TestResults/**/coverage.cobertura.xml"
              targetdir: "$(Build.SourcesDirectory)/TestResults"
              reporttypes: "HtmlInline_AzurePipelines;Cobertura;Badges"

          - task: PublishCodeCoverageResults@1
            displayName: "Publish Code Coverage"
            inputs:
              codeCoverageTool: "Cobertura"
              summaryFileLocation: "$(Build.SourcesDirectory)/TestResults/Cobertura.xml"
              reportDirectory: "$(Build.SourcesDirectory)/coverage"
              additionalCodeCoverageFiles: "$(Build.SourcesDirectory)/coveragereport*.html"

          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: "publish"
              publishWebProjects: true
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: false

          - task: PublishBuildArtifacts@1
            displayName: "Publish .NET Artifacts"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/ASM.Api"
              ArtifactName: "api"
            condition: succeededOrFailed()

          - script: |
              cd $(reactAppPath)
              npm install
            displayName: "Install npm dependencies"

          - script: |
              cd $(reactAppPath)
              npm run build
            displayName: "Build React App"

          - task: PublishBuildArtifacts@1
            displayName: "Publish React Artifacts"
            inputs:
              PathtoPublish: "$(reactAppPath)/dist"
              ArtifactName: "ui"
            condition: succeededOrFailed()
